name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master # 监听 master 分支的推送

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install and Build
        run: |
          npm install
          npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist # build 生成的目录
          branch: gh-pages # 部署到 gh-pages 分支
